### ISSUE TITLE
Panel color

### ISSUE THREAD

**Issue by stillesjo** [99xt/Sea-green-theme#4]
Edit: Updated screenshot
This doesn't look right...

![image](https://user-images.githubusercontent.com/2507506/35735513-62ee5e98-0825-11e8-9bb0-34af84e976a3.png)

Workaround by adding this to your preferences:
```json
    "workbench.colorCustomizations": {
        "panel.background": "#0a1018"
    },
```

**Comment by raashidA** [comment]
Thank you @stillesjo it's fixed in the last update.
